server:
  port: 18585

spring:
  application:
    name: emode-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
#    openai:
  #      api-key: sk-e4e1789998b442b6ab88ab4a6216c79a
  #      base-url: https://api.deepseek.com
  #      chat:
  #        options:
  #          model: deepseek-chat
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
